name: PullRequest

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Validation

    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Testing....display available Xcodes on the Server
        run: ls /Applications | grep Xcode

      - name: Force xcode 11 
        run: sudo xcode-select -switch /Applications/Xcode_11.5.app

      - name: List Simulators
        run: xcrun instruments -s
      
      - name: List SDK
        run: xcodebuild -showsdks
        
      - name: Build and test
        run: |
          swift run --package-path scripts/ContentTools ContentTools
